INSERT INTO USERS (ID, NAME, AUTHKEY) VALUES('admin', 'admin', '1234');
INSERT INTO USERS (ID, NAME, AUTHKEY) VALUES('admin1', 'admin1', '1234');
INSERT INTO USERS (ID, NAME, AUTHKEY) VALUES('admin2', 'admin2', '1234');

INSERT INTO QNA (CUSTOMER_ID, NAME, TITLE, CONTENTS, CREATEDAT, STATUS, PASSWORD)
VALUES ('user1', '1번입니다.', '문의1', '왜 안되죠', CURRENT_TIMESTAMP(), 'submit', '1234');

INSERT INTO QNA (CUSTOMER_ID, NAME, TITLE, CONTENTS, CREATEDAT, STATUS, PASSWORD)
VALUES ('user2', '2번입니다.', '문의2', '왜 안되죠', CURRENT_TIMESTAMP(), 'submit', '1234');

INSERT INTO QNA (CUSTOMER_ID, NAME, TITLE, CONTENTS, CREATEDAT, STATUS, PASSWORD, MANAGERID)
VALUES ('user3', '3번입니다.', '문의3', '왜 안되죠', CURRENT_TIMESTAMP(), 'assign', '1234', 'admin');

INSERT INTO QNA (CUSTOMER_ID, NAME, TITLE, CONTENTS, CREATEDAT, STATUS, PASSWORD, MANAGERID)
VALUES ('user3', '3번입니다.', '문의4', '왜 안되죠', CURRENT_TIMESTAMP(), 'assign', '1234', 'admin1');