CREATE TABLE USERS (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255),
	AUTHKEY VARCHAR(255)
);
	
CREATE TABLE QNA COMMENT 'Q&A' (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	CUSTOMER_ID VARCHAR(255) NOT NULL COMMENT '고객ID',
	NAME		VARCHAR(255) COMMENT '고객 이름',
	TITLE	VARCHAR(255) COMMENT '제목',
	CONTENTS	TEXT COMMENT '문의 내용',
	CREATEDAT	DATETIME COMMENT '작성 일시',	
	STATUS	CHAR(12) check(STATUS IN ('submit', 'assign', 'complete')),
	MANAGERID VARCHAR(255),
	ASSIGNEDAT DATETIME,
	PASSWORD VARCHAR(255),	
	foreign key (MANAGERID) REFERENCES USERS(ID)
	
);

CREATE TABLE ANSWER (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REPLY TEXT,
	QNA_ID INTEGER,
	CREATEDAT DATETIME,	
	FOREIGN KEY (QNA_ID) REFERENCES QNA(ID)
);